apiVersion: v2
name: one-chart
description: A Helm chart for Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "1.16.0"

dependencies:
  - name: media
    version: 0.1.0
    repository: "file://../media"
  - name: powerdns
    version: 0.1.0
    repository: "file://../powerdns"
    import-values:
      - child: powerdns
        parent: powerdns.powerdns
      - child: service
        parent: powerdns.service
      - child: zone
        parent: powerdns.zone
  # need to add the bitname chart repo as well
  - name: external-dns
    version: 6.12.1
    repository: "https://charts.bitnami.com/bitnami"
  #  import-values:
  #    - child: sources
  #      parent: external-dns.sources
  #    - child: provider
  #      parent: external-dns.provider
  #    - child: pdns
  #      parent: external-dns.pdns
  #    - child: domainFilters
  #      parent: external-dns.domainFilters
  #    - child: policy
  #      parent: external-dns.policy
